# TELEGRAM
TELEGRAM_TOKEN = "YOUR TELEGRAM TOKEN"
CHANNEL_ID = "YOUR CHANNEL ID"

# AMAZON
AMAZON_ACCESS_KEY = "YOUR AMAZON ACCESS KEY FROM AFFILIATE PROGRAM"
AMAZON_SECRET_KEY = "YOUR AMAZON SECRET KEY FROM AFFILIATE PROGRAM"
PARTNER_TAG = "YOUR REFFERAL TAG FROM AFFILIATE PROGRAM"
AMAZON_HOST = "webservices.amazon.it" #change to your country
AMAZON_REGION = "eu-west-1" #change to your country

